// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Boat

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_compass;
lv_obj_t * ui_Indicator;
lv_obj_t * ui_Container1;
lv_obj_t * ui_lbl_degree;
lv_obj_t * ui_lbl_direction;
lv_obj_t * ui_Divider01;
lv_obj_t * ui_Divider02;
lv_obj_t * ui_Gradient01;
lv_obj_t * ui_Container2;
lv_obj_t * ui_lbl_speed;
lv_obj_t * ui_lbl_unit;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_group_[2] = {&ui_img_group_2_png, &ui_img_group_3_png};
const lv_img_dsc_t * ui_imgset_line_[1] = {&ui_img_line_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
