// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Boat

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_compass = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_compass, &ui_img_compass_final_png);
    lv_obj_set_width(ui_compass, LV_SIZE_CONTENT);   /// 1025
    lv_obj_set_height(ui_compass, LV_SIZE_CONTENT);    /// 68
    lv_obj_set_x(ui_compass, 0);
    lv_obj_set_y(ui_compass, 42);
    lv_obj_add_flag(ui_compass, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_compass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Indicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Indicator, &ui_img_indicator_png);
    lv_obj_set_width(ui_Indicator, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_Indicator, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Indicator, 0);
    lv_obj_set_y(ui_Indicator, -78);
    lv_obj_set_align(ui_Indicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Indicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 113);
    lv_obj_set_height(ui_Container1, 34);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -141);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_degree = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_lbl_degree, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_lbl_degree, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_lbl_degree, -16);
    lv_obj_set_y(ui_lbl_degree, 0);
    lv_obj_set_align(ui_lbl_degree, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_degree, "0°");
    lv_obj_set_style_text_color(ui_lbl_degree, lv_color_hex(0xFE6A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_degree, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_degree, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_direction = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_lbl_direction, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_direction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_direction, 4);
    lv_obj_set_y(ui_lbl_direction, 0);
    lv_obj_set_align(ui_lbl_direction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_direction, "N");
    lv_obj_set_style_text_color(ui_lbl_direction, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_direction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_direction, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider01 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Divider01, &ui_img_line_1_png);
    lv_obj_set_width(ui_Divider01, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Divider01, LV_SIZE_CONTENT);    /// 4
    lv_obj_set_x(ui_Divider01, 0);
    lv_obj_set_y(ui_Divider01, -120);
    lv_obj_set_align(ui_Divider01, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Divider01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Divider01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Divider02 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Divider02, &ui_img_line_1_png);
    lv_obj_set_width(ui_Divider02, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Divider02, LV_SIZE_CONTENT);    /// 4
    lv_obj_set_x(ui_Divider02, 0);
    lv_obj_set_y(ui_Divider02, -48);
    lv_obj_set_align(ui_Divider02, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Divider02, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Divider02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Gradient01 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Gradient01, &ui_img_gradient_png);
    lv_obj_set_width(ui_Gradient01, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Gradient01, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_Gradient01, 0);
    lv_obj_set_y(ui_Gradient01, -101);
    lv_obj_set_align(ui_Gradient01, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gradient01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gradient01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 233);
    lv_obj_set_height(ui_Container2, 112);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 67);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbl_speed = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lbl_speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_speed, 0);
    lv_obj_set_y(ui_lbl_speed, -4);
    lv_obj_set_align(ui_lbl_speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_speed, "0");
    lv_obj_set_style_text_color(ui_lbl_speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_speed, &ui_font_Font100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl_unit = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lbl_unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl_unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl_unit, 0);
    lv_obj_set_y(ui_lbl_unit, 40);
    lv_obj_set_align(ui_lbl_unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl_unit, "Knots");
    lv_obj_set_style_text_color(ui_lbl_unit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl_unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl_unit, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
